// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACkZblofGOYAFEyyHDdHFXhlC6P670bEM',
    appId: '1:863227552301:web:572a3d8a5447bc59234ea4',
    messagingSenderId: '863227552301',
    projectId: 'social-media-app-bloc-fa8f5',
    authDomain: 'social-media-app-bloc-fa8f5.firebaseapp.com',
    storageBucket: 'social-media-app-bloc-fa8f5.appspot.com',
    measurementId: 'G-CETV20S0QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLe_wVkpXVoKhel2y2IH6IqxOGUTtUreQ',
    appId: '1:863227552301:android:e17ee8dd8d00e3a3234ea4',
    messagingSenderId: '863227552301',
    projectId: 'social-media-app-bloc-fa8f5',
    storageBucket: 'social-media-app-bloc-fa8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFBS6A7_7Bc26nkjghH0pWlVtCny6nT4',
    appId: '1:863227552301:ios:7e170785141c5b7a234ea4',
    messagingSenderId: '863227552301',
    projectId: 'social-media-app-bloc-fa8f5',
    storageBucket: 'social-media-app-bloc-fa8f5.appspot.com',
    iosBundleId: 'com.example.socialMediaAppBloc001',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFBS6A7_7Bc26nkjghH0pWlVtCny6nT4',
    appId: '1:863227552301:ios:7e170785141c5b7a234ea4',
    messagingSenderId: '863227552301',
    projectId: 'social-media-app-bloc-fa8f5',
    storageBucket: 'social-media-app-bloc-fa8f5.appspot.com',
    iosBundleId: 'com.example.socialMediaAppBloc001',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACkZblofGOYAFEyyHDdHFXhlC6P670bEM',
    appId: '1:863227552301:web:e0193d3224c96423234ea4',
    messagingSenderId: '863227552301',
    projectId: 'social-media-app-bloc-fa8f5',
    authDomain: 'social-media-app-bloc-fa8f5.firebaseapp.com',
    storageBucket: 'social-media-app-bloc-fa8f5.appspot.com',
    measurementId: 'G-G0BNNM0L6L',
  );
}
